# Generated by Django 4.2 on 2024-01-04 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_delete_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
